// Code generated by "core generate -add-types -gosl"; DO NOT EDIT.

package motion

import (
	"cogentcore.org/core/enums"
)

var _DirectionsValues = []Directions{0, 1, 2, 3}

// DirectionsN is the highest valid value for type Directions, plus one.
//
//gosl:start
const DirectionsN Directions = 4

//gosl:end

var _DirectionsValueMap = map[string]Directions{`Left`: 0, `Right`: 1, `Down`: 2, `Up`: 3}

var _DirectionsDescMap = map[Directions]string{0: ``, 1: ``, 2: ``, 3: ``}

var _DirectionsMap = map[Directions]string{0: `Left`, 1: `Right`, 2: `Down`, 3: `Up`}

// String returns the string representation of this Directions value.
func (i Directions) String() string { return enums.String(i, _DirectionsMap) }

// SetString sets the Directions value from its string representation,
// and returns an error if the string is invalid.
func (i *Directions) SetString(s string) error {
	return enums.SetString(i, s, _DirectionsValueMap, "Directions")
}

// Int64 returns the Directions value as an int64.
func (i Directions) Int64() int64 { return int64(i) }

// SetInt64 sets the Directions value from an int64.
func (i *Directions) SetInt64(in int64) { *i = Directions(in) }

// Desc returns the description of the Directions value.
func (i Directions) Desc() string { return enums.Desc(i, _DirectionsDescMap) }

// DirectionsValues returns all possible values for the type Directions.
func DirectionsValues() []Directions { return _DirectionsValues }

// Values returns all possible values for the type Directions.
func (i Directions) Values() []enums.Enum { return enums.Values(_DirectionsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Directions) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Directions) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "Directions")
}
