// Code generated by "core generate -add-types"; DO NOT EDIT.

package motion

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/v1vision/motion.Params", IDName: "params", Doc: "Params has the motion parameters.", Directives: []types.Directive{{Tool: "go", Directive: "generate", Args: []string{"core", "generate", "-add-types"}}}, Fields: []types.Field{{Name: "SlowTau", Doc: "SlowTau is the time constant (in frames) for integrating\nslow inhibitory inputs."}, {Name: "FastTau", Doc: "FastTau is the time constant (in frames) for integrating\nfast excitatory inputs."}, {Name: "Gain", Doc: "Gain is multiplier on difference."}}})
