// Code generated by "core generate -add-types -gosl"; DO NOT EDIT.

package motion

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/v1vision/motion.Params", IDName: "params", Doc: "Params has the motion parameters.", Directives: []types.Directive{{Tool: "go", Directive: "generate", Args: []string{"core", "generate", "-add-types", "-gosl"}}}, Fields: []types.Field{{Name: "SlowTau", Doc: "SlowTau is the time constant (in frames) for integrating\nslow inhibitory inputs."}, {Name: "FastTau", Doc: "FastTau is the time constant (in frames) for integrating\nfast excitatory inputs."}, {Name: "Gain", Doc: "Gain is multiplier on the opponent difference for Star computation."}, {Name: "FullGain", Doc: "FullGain is multiplier for FullField"}, {Name: "IntegTau", Doc: "IntegTau is the integration time constant for integrating\nthe normalization and full field values over frames, to get\na more consistent value."}, {Name: "NormInteg", Doc: "NormInteg is the integrated normalization value -- updated in FullFieldInteg"}, {Name: "DoGSumScalarIndex", Doc: "DoGSumScalarIndex is the index into the V1Vision Scalars output for\nSum of DoG activity, used for normalizing."}, {Name: "FFScalarIndex", Doc: "FFScalarIndex is the index into the V1Vision Scalars output for FullField"}}})
