// Code generated by "gosl"; DO NOT EDIT
// kernel: EdgeAverage

// // CurOp is the current operation to perform. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> CurOp: array<Op>;
// // Filters are one general stack of rendered filters, sized to the max of each // of the inner dimensional values: [FilterTypes][FilterN][Y][X] // FilterTypes = different filter types (DoG, Gabor, etc) // FilterN = number of filters within the group (On, Off, angle, etc) // Y, X = sizes. 
// // Images are float-valued image data: // [ImageNo][NData][RGB][Y][X], // sized to the max of each inner-dimensional value (RGB=3, // if more needed, use additional ImageNo) 
@group(2) @binding(0)
var<storage, read_write> Images: array<f32>;
@group(2) @binding(3)
var<storage, read_write> Scalars: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	EdgeAverage(idx);
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}


//////// import: "vars.go"

//////// import: "colorspace-lms.go"
/*
func LMSToXYZ_CAT02(l, m, s f32) (x, y, z f32) {
    x = 1.096124 * l + 0.4296f * Y + -0.1624f * Z;
    y = -0.7036f * X + 1.6975f * Y + 0.0061f * Z;
    z = 0.0030f * X + 0.0136f * Y + 0.9834 * Z;
  }
*/
/*
  func LMStoXYZ_HPE(float& X, float& Y, float& Z,
                                    L, M, S) {
    X = 1.096124f * L + 0.4296f * Y + -0.1624f * Z;
    Y = -0.7036f * X + 1.6975f * Y + 0.0061f * Z;
    Z = 0.0030f * X + 0.0136f * Y + 0.9834 * Z;
  }
*/

//////// import: "colorspace-srgb.go"

//////// import: "complex.go"

//////// import: "convolve.go"

//////// import: "enumgen.go"
const GPUVarsN: GPUVars = 8;
const InhibVarsN: InhibVars = 9;
const OperationsN: Operations = 24;

//////// import: "fffb-fffb.go"
struct FFFB {
	On: i32,
	Gi: f32,
	FF: f32,
	FB: f32,
	FBTau: f32,
	MaxVsAvg: f32,
	FF0: f32,
	FBDt: f32,
}

//////// import: "geom.go"
struct Geom {
	In: vec4<i32>,
	Out: vec4<i32>,
	Border: vec4<i32>,
	Spacing: vec4<i32>,
	FilterSize: vec4<i32>,
	FilterLt: vec4<i32>,
	FilterRt: vec4<i32>,
}

//////// import: "image.go"
fn EdgeAverage(i: u32) { //gosl:kernel
	let op = CurOp[0];
	if (i >= op.NData) {
		return;
	}
	var ni = i32(i);
	var padWidth = op.IntArg1;
	var sY = op.Geom.In.y - 2*padWidth;
	var sX = op.Geom.In.x - 2*padWidth;
	var avg: vec3<f32>;
	for (var y=0; y<sY; y++) {
		var oy = y + padWidth;
		for (var rgb=0; rgb<i32(3); rgb++) {
			var v = Dim3(avg, rgb) + Images[Index5D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], TensorStrides[14], u32(op.InImage), u32(ni), u32(rgb), u32(oy), u32(padWidth))] + Images[Index5D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], TensorStrides[14], u32(op.InImage), u32(ni), u32(rgb), u32(oy), u32(padWidth + sX - 1))];
			avg = SetDim3(avg, rgb, v);
		}
	}
	for (var x=0; x<sX; x++) {
		var ox = x + padWidth;
		for (var rgb=0; rgb<i32(3); rgb++) {
			var v = Dim3(avg, rgb) + Images[Index5D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], TensorStrides[14], u32(op.InImage), u32(ni), u32(rgb), u32(padWidth), u32(ox))] + Images[Index5D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], TensorStrides[14], u32(op.InImage), u32(ni), u32(rgb), u32(padWidth + sY - 1), u32(ox))];
			avg = SetDim3(avg, rgb, v);
		}
	}
	var n = 2 * (sX + sY);
	for (var rgb=0; rgb<i32(3); rgb++) {
		Scalars[Index2D(TensorStrides[40], TensorStrides[41], u32(i32(op.OutScalar) + rgb), u32(ni))] = Dim3(avg, rgb) / f32(n);
	}
}

//////// import: "inhib.go"
alias InhibVars = i32; //enums:enum
const  FFi: InhibVars = 0;
const  FBi: InhibVars = 1;
const  Gi: InhibVars = 2;
const  GiOrig: InhibVars = 3;
const  LayGi: InhibVars = 4;
const  GeAvg: InhibVars = 5;
const  GeMax: InhibVars = 6;
const  ActAvg: InhibVars = 7;
const  ActMax: InhibVars = 8;

//////// import: "kwta-chans.go"
struct Chans {
	E: f32,
	L: f32,
	I: f32,
	K: f32,
}

//////// import: "kwta-kwta.go"
struct KWTA {
	On: i32,
	Iters: i32,
	DelActThr: f32,
	ActTau: f32,
	Layer: FFFB,
	Pool: FFFB,
	XX1: Params,
	Gbar: Chans,
	Erev: Chans,
	ErevSubThr: Chans,
	ThrSubErev: Chans,
	ActDt: f32,
	pad: f32,
	pad1: f32,
	pad2: f32,
}

//////// import: "kwta.go"

//////// import: "logrenorm.go"

//////// import: "math32-fastexp.go"

//////// import: "maxpool.go"

//////// import: "motion.go"

//////// import: "nxx1-nxx1.go"
struct Params {
	Thr: f32,
	Gain: f32,
	NVar: f32,
	VmActThr: f32,
	SigMult: f32,
	SigMultPow: f32,
	SigGain: f32,
	InterpRange: f32,
	GainCorRange: f32,
	GainCor: f32,
	SigGainNVar: f32,
	SigMultEff: f32,
	SigValAt0: f32,
	InterpVal: f32,
	pad: f32,
	pad1: f32,
}

//////// import: "op.go"
alias Operations = i32; //enums:enum
const  NoOp: Operations = 0;
const  WrapPad: Operations = 1;
const  EdgeAvg: Operations = 2;
const  FadePad: Operations = 3;
const  LMSOpponents: Operations = 4;
const  LMSComponents: Operations = 5;
const  ConvolveImage: Operations = 6;
const  ConvolveDiff: Operations = 7;
const  LogValues: Operations = 8;
const  MaxScalar: Operations = 9;
const  SumScalar: Operations = 10;
const  MeanScalar: Operations = 11;
const  NormDiv: Operations = 12;
const  NeighInhib4: Operations = 13;
const  KWTAInhib: Operations = 14;
const  MaxPool: Operations = 15;
const  MaxPolarity: Operations = 16;
const  MaxCopy: Operations = 17;
const  LenSum4: Operations = 18;
const  EndStop4: Operations = 19;
const  To4D: Operations = 20;
const  MotionIntegrate: Operations = 21;
const  MotionStar: Operations = 22;
const  MotionFullField: Operations = 23;
struct Op {
	Op: Operations,
	NData: u32,
	RunN: u32,
	InImage: i32,
	InImageRGB: i32,
	InValue: i32,
	InValue2: i32,
	OutValue: i32,
	OutValue4D: i32,
	OutImage: i32,
	OutImage2: i32,
	FilterType: i32,
	FilterN: i32,
	FloatArg1: f32,
	FloatArg2: f32,
	FloatArg3: f32,
	IntArg1: i32,
	InScalar: i32,
	OutScalar: i32,
	Inhibs: i32,
	KWTA: i32,
	pad: i32,
	pad1: i32,
	pad2: i32,
	Geom: Geom,
}

//////// import: "scalar.go"

//////// import: "slmath-math.go"
const Pi = 3.141592653589793;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"

//////// import: "slmath-vector2.go"

//////// import: "slmath-vector3.go"
fn Dim3(v: vec3<f32>, dim: i32) -> f32 {
	if (dim == 0) {
		return v.x;
	}
	if (dim == 1) {
		return v.y;
	}return v.z;
}
fn SetDim3(v: vec3<f32>, dim: i32, val: f32) -> vec3<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x = val;
	}
	if (dim == 1) {
		nv.y = val;
	}
	if (dim == 2) {
		nv.z = val;
	}return nv;
}

//////// import: "to4d.go"