// Code generated by "gosl"; DO NOT EDIT
// kernel: KWTAIterLayer

// // CurOp is the current operation to perform. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> CurOp: array<Op>;
@group(0) @binding(2)
var<storage, read> KWTAs: array<KWTA>;
// // Filters are one general stack of rendered filters, sized to the max of each // of the inner dimensional values: [FilterTypes][FilterN][Y][X] // FilterTypes = different filter types (DoG, Gabor, etc) // FilterN = number of filters within the group (On, Off, angle, etc) // Y, X = sizes. 
// // Images are float-valued image data: [ImageNo][RGB][Y][X], // sized to the max of each inner-dimensional value (RGB=3, // if more needed, use additional ImageNo) 
@group(2) @binding(2)
var<storage, read_write> Values4D: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	KWTAIterLayer(idx);
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "convolve.go"

//////// import: "enumgen.go"
const GPUVarsN: GPUVars = 7;
const InhibVarsN: InhibVars = 9;
const OperationsN: Operations = 14;

//////// import: "fffb-fffb.go"
struct FFFB {
	On: i32,
	Gi: f32,
	FF: f32,
	FB: f32,
	FBTau: f32,
	MaxVsAvg: f32,
	FF0: f32,
	FBDt: f32,
}
fn FFFB_FFInhib(fb: FFFB, avgGe: f32,maxGe: f32) -> f32 {
	var ffNetin = avgGe + fb.MaxVsAvg*(maxGe-avgGe);
	var ffi: f32;
	if (ffNetin > fb.FF0) {
		ffi = fb.FF * (ffNetin - fb.FF0);
	}return ffi;
}
fn FFFB_FBInhib(fb: FFFB, avgAct: f32) -> f32 {
	return fb.FB * avgAct;
}
fn FFFB_FBUpdt(fb: FFFB, fbi: f32, newFbi: f32) -> f32 {
	var nfb = fbi;
	nfb += fb.FBDt * (newFbi - nfb);return nfb;
}

//////// import: "geom.go"
struct Geom {
	In: vec4<i32>,
	Out: vec4<i32>,
	Border: vec4<i32>,
	Spacing: vec4<i32>,
	FilterSz: vec4<i32>,
	FilterLt: vec4<i32>,
	FilterRt: vec4<i32>,
}

//////// import: "image.go"

//////// import: "inhib.go"
alias InhibVars = i32; //enums:enum
const  FFi: InhibVars = 0;
const  FBi: InhibVars = 1;
const  Gi: InhibVars = 2;
const  GiOrig: InhibVars = 3;
const  LayGi: InhibVars = 4;
const  GeAvg: InhibVars = 5;
const  GeMax: InhibVars = 6;
const  ActAvg: InhibVars = 7;
const  ActMax: InhibVars = 8;

//////// import: "kwta-chans.go"
struct Chans {
	E: f32,
	L: f32,
	I: f32,
	K: f32,
}

//////// import: "kwta-kwta.go"
struct KWTA {
	On: i32,
	Iters: i32,
	DelActThr: f32,
	ActTau: f32,
	Layer: FFFB,
	Pool: FFFB,
	XX1: Params,
	Gbar: Chans,
	Erev: Chans,
	ErevSubThr: Chans,
	ThrSubErev: Chans,
	ActDt: f32,
	pad: f32,
	pad1: f32,
	pad2: f32,
}

//////// import: "kwta.go"
fn KWTAIterLayer(i: u32) { //gosl:kernel
	if (i != 0) {
		return;
	}
	let op = CurOp[0];
	var lyi = i32(op.Geom.Out.y);
	var ln = f32(op.Geom.Out.y * op.Geom.Out.x);
	let kp = KWTAs[u32(op.KWTA)];
	var geAvg = f32(0);
	var geMax = f32(0);
	var actAvg = f32(0);
	var actMax = f32(0);
	for (var yo=0; yo<op.Geom.Out.y; yo++) {
		for (var xo=0; xo<op.Geom.Out.x; xo++) {
			var gavg = Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(yo), u32(xo), u32(0), u32(GeAvg))];
			var gmx = Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(yo), u32(xo), u32(0), u32(GeMax))];
			var aavg = Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(yo), u32(xo), u32(0), u32(ActAvg))];
			var amx = Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(yo), u32(xo), u32(0), u32(ActMax))];
			geAvg += gavg;
			geMax = max(geMax, gmx);
			actAvg += aavg;
			actMax = max(actMax, amx);
		}
	}
	geAvg /= ln;
	actAvg /= ln;
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(GeAvg))] = geAvg;
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(GeMax))] = geMax;
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(ActAvg))] = actAvg;
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(ActMax))] = actMax;
	var fbi = Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(FBi))];
	var ffi = FFFB_FFInhib(kp.Layer, geAvg, geMax);
	var newFBi = FFFB_FBInhib(kp.Layer, actAvg);
	fbi = FFFB_FBUpdt(kp.Layer, fbi, newFBi);
	if (kp.Layer.On == 0) {
		ffi = f32(0.0);
		fbi = f32(0.0);
	}
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(FFi))] = ffi;
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(FBi))] = fbi;
	var gi = kp.Layer.Gi * (ffi + fbi);
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(Gi))] = gi;
	Values4D[Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33],
	TensorStrides[34], u32(op.OutValue4D), u32(lyi), u32(0), u32(0), u32(GiOrig))] = gi;
}

//////// import: "logrenorm.go"

//////// import: "math32-fastexp.go"

//////// import: "math32-vector2.go"
struct Vector2 {
	X: f32,
	Y: f32,
}

//////// import: "math32-vector2i.go"
struct Vector2i {
	X: i32,
	Y: i32,
}

//////// import: "maxpool.go"

//////// import: "motion.go"

//////// import: "nxx1-nxx1.go"
struct Params {
	Thr: f32,
	Gain: f32,
	NVar: f32,
	VmActThr: f32,
	SigMult: f32,
	SigMultPow: f32,
	SigGain: f32,
	InterpRange: f32,
	GainCorRange: f32,
	GainCor: f32,
	SigGainNVar: f32,
	SigMultEff: f32,
	SigValAt0: f32,
	InterpVal: f32,
	pad: f32,
	pad1: f32,
}

//////// import: "op.go"
alias Operations = i32; //enums:enum
const  NoOp: Operations = 0;
const  WrapPad: Operations = 1;
const  ConvolveImage: Operations = 2;
const  LogValues: Operations = 3;
const  MaxScalar: Operations = 4;
const  SumScalar: Operations = 5;
const  MeanScalar: Operations = 6;
const  NormDiv: Operations = 7;
const  NeighInhib: Operations = 8;
const  KWTAInhib: Operations = 9;
const  MaxPool: Operations = 10;
const  MotionIntegrate: Operations = 11;
const  MotionStar: Operations = 12;
const  MotionFullField: Operations = 13;
struct Op {
	Op: Operations,
	RunN: u32,
	InImage: i32,
	InImageRGB: i32,
	InValue: i32,
	OutValue: i32,
	OutValue4D: i32,
	OutImage: i32,
	FilterType: i32,
	FilterN: i32,
	FloatArg1: f32,
	FloatArg2: f32,
	IntArg1: i32,
	InScalar: i32,
	OutScalar: i32,
	KWTA: i32,
	Geom: Geom,
}