// Code generated by "gosl"; DO NOT EDIT
// kernel: KWTAIterLayerY

// // CurOp is the current operation to perform. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> CurOp: array<Op>;
@group(0) @binding(2)
var<storage, read> KWTAs: array<KWTA>;
// // Filters are one general stack of rendered filters, sized to the max of each // of the inner dimensional values: [FilterTypes][FilterN][Y][X] // FilterTypes = different filter types (DoG, Gabor, etc) // FilterN = number of filters within the group (On, Off, angle, etc) // Y, X = sizes. 
// // Images are float-valued image data: // [ImageNo][NData][RGB][Y][X], // sized to the max of each inner-dimensional value (RGB=3, // if more needed, use additional ImageNo) 
@group(2) @binding(4)
var<storage, read_write> Inhibs: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	KWTAIterLayerY(idx);
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "colorspace-lms.go"
/*
func LMSToXYZ_CAT02(l, m, s f32) (x, y, z f32) {
    x = 1.096124 * l + 0.4296f * Y + -0.1624f * Z;
    y = -0.7036f * X + 1.6975f * Y + 0.0061f * Z;
    z = 0.0030f * X + 0.0136f * Y + 0.9834 * Z;
  }
*/
/*
  func LMStoXYZ_HPE(float& X, float& Y, float& Z,
                                    L, M, S) {
    X = 1.096124f * L + 0.4296f * Y + -0.1624f * Z;
    Y = -0.7036f * X + 1.6975f * Y + 0.0061f * Z;
    Z = 0.0030f * X + 0.0136f * Y + 0.9834 * Z;
  }
*/

//////// import: "colorspace-srgb.go"

//////// import: "complex.go"

//////// import: "convolve.go"

//////// import: "enumgen.go"
const GPUVarsN: GPUVars = 8;
const InhibVarsN: InhibVars = 9;
const OperationsN: Operations = 24;

//////// import: "fffb-fffb.go"
struct FFFB {
	On: i32,
	Gi: f32,
	FF: f32,
	FB: f32,
	FBTau: f32,
	MaxVsAvg: f32,
	FF0: f32,
	FBDt: f32,
}
fn FFFB_FFInhib(fb: FFFB, avgGe: f32,maxGe: f32) -> f32 {
	var ffNetin = avgGe + fb.MaxVsAvg*(maxGe-avgGe);
	var ffi: f32;
	if (ffNetin > fb.FF0) {
		ffi = fb.FF * (ffNetin - fb.FF0);
	}return ffi;
}
fn FFFB_FBInhib(fb: FFFB, avgAct: f32) -> f32 {
	return fb.FB * avgAct;
}
fn FFFB_FBUpdt(fb: FFFB, fbi: f32, newFbi: f32) -> f32 {
	var nfb = fbi;
	nfb += fb.FBDt * (newFbi - nfb);
return nfb;
}

//////// import: "geom.go"
struct Geom {
	In: vec4<i32>,
	Out: vec4<i32>,
	Border: vec4<i32>,
	Spacing: vec4<i32>,
	FilterSize: vec4<i32>,
	FilterLt: vec4<i32>,
	FilterRt: vec4<i32>,
}

//////// import: "image.go"

//////// import: "inhib.go"
alias InhibVars = i32; //enums:enum
const  FFi: InhibVars = 0;
const  FBi: InhibVars = 1;
const  Gi: InhibVars = 2;
const  GiOrig: InhibVars = 3;
const  LayGi: InhibVars = 4;
const  GeAvg: InhibVars = 5;
const  GeMax: InhibVars = 6;
const  ActAvg: InhibVars = 7;
const  ActMax: InhibVars = 8;

//////// import: "kwta-chans.go"
struct Chans {
	E: f32,
	L: f32,
	I: f32,
	K: f32,
}

//////// import: "kwta-kwta.go"
struct KWTA {
	On: i32,
	Iters: i32,
	DelActThr: f32,
	ActTau: f32,
	Layer: FFFB,
	Pool: FFFB,
	XX1: Params,
	Gbar: Chans,
	Erev: Chans,
	ErevSubThr: Chans,
	ThrSubErev: Chans,
	ActDt: f32,
	pad: f32,
	pad1: f32,
	pad2: f32,
}

//////// import: "kwta.go"
fn KWTAIterLayerY(i: u32) { //gosl:kernel
	let op = CurOp[0];
	if (i >= op.NData) {
		return;
	}
	var ni = i32(i);
	var szY = op.Geom.Out.y;
	var szX = op.Geom.Out.x;
	var ln = f32(szY);
	var geAvg = f32(0);
	var geMax = f32(0);
	var actAvg = f32(0);
	var actMax = f32(0);
	for (var yo=0; yo<szY; yo++) {
		var gavg = Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(yo), u32(szX), u32(GeAvg))];
		var gmx = Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(yo), u32(szX), u32(GeMax))];
		var aavg = Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(yo), u32(szX), u32(ActAvg))];
		var amx = Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(yo), u32(szX), u32(ActMax))];
		geAvg += gavg;
		geMax = max(geMax, gmx);
		actAvg += aavg;
		actMax = max(actMax, amx);
	}
	geAvg /= ln;
	actAvg /= ln;
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(GeAvg))] = geAvg;
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(GeMax))] = geMax;
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(ActAvg))] = actAvg;
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(ActMax))] = actMax;
	let kp = KWTAs[u32(op.KWTA)];
	var fbi = Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(FBi))];
	var ffi = FFFB_FFInhib(kp.Layer, geAvg, geMax);
	var newFBi = FFFB_FBInhib(kp.Layer, actAvg);
	fbi = FFFB_FBUpdt(kp.Layer, fbi, newFBi);
	if (kp.Layer.On == 0) {
		ffi = f32(0.0);
		fbi = f32(0.0);
	}
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(FFi))] = ffi;
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(FBi))] = fbi;
	var gi = kp.Layer.Gi * (ffi + fbi);
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(Gi))] = gi;
	Inhibs[Index5D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53],
	TensorStrides[54], u32(op.Inhibs), u32(ni), u32(szY), u32(0), u32(GiOrig))] = gi;
}

//////// import: "logrenorm.go"

//////// import: "math32-fastexp.go"

//////// import: "maxpool.go"

//////// import: "motion.go"

//////// import: "nxx1-nxx1.go"
struct Params {
	Thr: f32,
	Gain: f32,
	NVar: f32,
	VmActThr: f32,
	SigMult: f32,
	SigMultPow: f32,
	SigGain: f32,
	InterpRange: f32,
	GainCorRange: f32,
	GainCor: f32,
	SigGainNVar: f32,
	SigMultEff: f32,
	SigValAt0: f32,
	InterpVal: f32,
	pad: f32,
	pad1: f32,
}

//////// import: "op.go"
alias Operations = i32; //enums:enum
const  NoOp: Operations = 0;
const  WrapPad: Operations = 1;
const  EdgeAvg: Operations = 2;
const  FadePad: Operations = 3;
const  LMSOpponents: Operations = 4;
const  LMSComponents: Operations = 5;
const  ConvolveImage: Operations = 6;
const  ConvolveDiff: Operations = 7;
const  LogValues: Operations = 8;
const  MaxScalar: Operations = 9;
const  SumScalar: Operations = 10;
const  MeanScalar: Operations = 11;
const  NormDiv: Operations = 12;
const  NeighInhib4: Operations = 13;
const  KWTAInhib: Operations = 14;
const  MaxPool: Operations = 15;
const  MaxPolarity: Operations = 16;
const  MaxCopy: Operations = 17;
const  LenSum4: Operations = 18;
const  EndStop4: Operations = 19;
const  To4D: Operations = 20;
const  MotionIntegrate: Operations = 21;
const  MotionStar: Operations = 22;
const  MotionFullField: Operations = 23;
struct Op {
	Op: Operations,
	NData: u32,
	RunN: u32,
	InImage: i32,
	InImageRGB: i32,
	InValue: i32,
	InValue2: i32,
	OutValue: i32,
	OutValue4D: i32,
	OutImage: i32,
	OutImage2: i32,
	FilterType: i32,
	FilterN: i32,
	FloatArg1: f32,
	FloatArg2: f32,
	FloatArg3: f32,
	IntArg1: i32,
	InScalar: i32,
	OutScalar: i32,
	Inhibs: i32,
	KWTA: i32,
	pad: i32,
	pad1: i32,
	pad2: i32,
	Geom: Geom,
}

//////// import: "scalar.go"

//////// import: "slmath-math.go"
const Pi = 3.141592653589793;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"

//////// import: "slmath-vector2.go"

//////// import: "slmath-vector3.go"

//////// import: "to4d.go"