// Code generated by "gosl"; DO NOT EDIT
// kernel: KWTAIterLayerX

// // CurOp is the current operation to perform. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> CurOp: array<Op>;
// // Filters are one general stack of rendered filters, sized to the max of each // of the inner dimensional values: [FilterTypes][FilterN][Y][X] // FilterTypes = different filter types (DoG, Gabor, etc) // FilterN = number of filters within the group (On, Off, angle, etc) // Y, X = sizes. 
// // Images are float-valued image data: [ImageNo][RGB][Y][X], // sized to the max of each inner-dimensional value (RGB=3, // if more needed, use additional ImageNo) 
@group(2) @binding(4)
var<storage, read_write> Inhibs: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	KWTAIterLayerX(idx);
}

fn Index4D(s0: u32, s1: u32, s2: u32, s3: u32, i0: u32, i1: u32, i2: u32, i3: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3;
}


//////// import: "vars.go"

//////// import: "colorspace-lms.go"
alias LMSComponents = i32; //enums:enum
const  LC: LMSComponents = 0;
const  MC: LMSComponents = 1;
const  SC: LMSComponents = 2;
const  LMC: LMSComponents = 3;
const  LvMC: LMSComponents = 4;
const  SvLMC: LMSComponents = 5;
const  GREY: LMSComponents = 6;
alias Opponents = i32; //enums:enum
const  WhiteBlack: Opponents = 0;
const  RedGreen: Opponents = 1;
const  BlueYellow: Opponents = 2;
/*
func LMSToXYZ_CAT02(l, m, s f32) (x, y, z f32) {
    x = 1.096124 * l + 0.4296f * Y + -0.1624f * Z;
    y = -0.7036f * X + 1.6975f * Y + 0.0061f * Z;
    z = 0.0030f * X + 0.0136f * Y + 0.9834 * Z;
  }
*/
/*
  func LMStoXYZ_HPE(float& X, float& Y, float& Z,
                                    L, M, S) {
    X = 1.096124f * L + 0.4296f * Y + -0.1624f * Z;
    Y = -0.7036f * X + 1.6975f * Y + 0.0061f * Z;
    Z = 0.0030f * X + 0.0136f * Y + 0.9834 * Z;
  }
*/

//////// import: "colorspace-srgb.go"

//////// import: "complex.go"

//////// import: "convolve.go"

//////// import: "enumgen.go"
const GPUVarsN: GPUVars = 8;
const InhibVarsN: InhibVars = 9;
const OperationsN: Operations = 21;

//////// import: "fffb-fffb.go"
struct FFFB {
	On: i32,
	Gi: f32,
	FF: f32,
	FB: f32,
	FBTau: f32,
	MaxVsAvg: f32,
	FF0: f32,
	FBDt: f32,
}

//////// import: "geom.go"
struct Geom {
	In: vec4<i32>,
	Out: vec4<i32>,
	Border: vec4<i32>,
	Spacing: vec4<i32>,
	FilterSz: vec4<i32>,
	FilterLt: vec4<i32>,
	FilterRt: vec4<i32>,
}

//////// import: "image.go"

//////// import: "inhib.go"
alias InhibVars = i32; //enums:enum
const  FFi: InhibVars = 0;
const  FBi: InhibVars = 1;
const  Gi: InhibVars = 2;
const  GiOrig: InhibVars = 3;
const  LayGi: InhibVars = 4;
const  GeAvg: InhibVars = 5;
const  GeMax: InhibVars = 6;
const  ActAvg: InhibVars = 7;
const  ActMax: InhibVars = 8;

//////// import: "kwta-chans.go"
struct Chans {
	E: f32,
	L: f32,
	I: f32,
	K: f32,
}

//////// import: "kwta-kwta.go"
struct KWTA {
	On: i32,
	Iters: i32,
	DelActThr: f32,
	ActTau: f32,
	Layer: FFFB,
	Pool: FFFB,
	XX1: Params,
	Gbar: Chans,
	Erev: Chans,
	ErevSubThr: Chans,
	ThrSubErev: Chans,
	ActDt: f32,
	pad: f32,
	pad1: f32,
	pad2: f32,
}

//////// import: "kwta.go"
fn KWTAIterLayerX(i: u32) { //gosl:kernel
	let op = CurOp[0];
	var szY = op.Geom.Out.y;
	var szX = op.Geom.Out.x;
	var yo = i32(i);
	if (yo >= szY) {
		return;
	}
	var ln = f32(szY);
	var geAvg = f32(0);
	var geMax = f32(0);
	var actAvg = f32(0);
	var actMax = f32(0);
	for (var xo=0; xo<szX; xo++) {
		var gavg = Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], u32(op.Inhibs), u32(yo), u32(xo), u32(GeAvg))];
		var gmx = Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], u32(op.Inhibs), u32(yo), u32(xo), u32(GeMax))];
		var aavg = Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], u32(op.Inhibs), u32(yo), u32(xo), u32(ActAvg))];
		var amx = Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], u32(op.Inhibs), u32(yo), u32(xo), u32(ActMax))];
		geAvg += gavg;
		geMax = max(geMax, gmx);
		actAvg += aavg;
		actMax = max(actMax, amx);
	}
	geAvg /= ln;
	actAvg /= ln;
	Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], u32(op.Inhibs), u32(yo), u32(szX), u32(GeAvg))] = geAvg;
	Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], u32(op.Inhibs), u32(yo), u32(szX), u32(GeMax))] = geMax;
	Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53], u32(op.Inhibs), u32(yo), u32(szX), u32(ActAvg))] = actAvg;
	Inhibs[Index4D(TensorStrides[50], TensorStrides[51], TensorStrides[52], TensorStrides[53],
	u32(op.Inhibs), u32(yo), u32(szX), u32(ActMax))] = actMax;
}

//////// import: "logrenorm.go"

//////// import: "math32-fastexp.go"

//////// import: "maxpool.go"

//////// import: "motion.go"

//////// import: "nxx1-nxx1.go"
struct Params {
	Thr: f32,
	Gain: f32,
	NVar: f32,
	VmActThr: f32,
	SigMult: f32,
	SigMultPow: f32,
	SigGain: f32,
	InterpRange: f32,
	GainCorRange: f32,
	GainCor: f32,
	SigGainNVar: f32,
	SigMultEff: f32,
	SigValAt0: f32,
	InterpVal: f32,
	pad: f32,
	pad1: f32,
}

//////// import: "op.go"
alias Operations = i32; //enums:enum
const  NoOp: Operations = 0;
const  WrapPad: Operations = 1;
const  FadePad: Operations = 2;
const  LMSImage: Operations = 3;
const  ConvolveImage: Operations = 4;
const  LogValues: Operations = 5;
const  MaxScalar: Operations = 6;
const  SumScalar: Operations = 7;
const  MeanScalar: Operations = 8;
const  NormDiv: Operations = 9;
const  NeighInhib4: Operations = 10;
const  KWTAInhib: Operations = 11;
const  MaxPool: Operations = 12;
const  MaxPolarity: Operations = 13;
const  MaxCopy: Operations = 14;
const  LenSum4: Operations = 15;
const  EndStop4: Operations = 16;
const  To4D: Operations = 17;
const  MotionIntegrate: Operations = 18;
const  MotionStar: Operations = 19;
const  MotionFullField: Operations = 20;
struct Op {
	Op: Operations,
	RunN: u32,
	InImage: i32,
	InImageRGB: i32,
	InValue: i32,
	InValue2: i32,
	OutValue: i32,
	OutValue4D: i32,
	OutImage: i32,
	FilterType: i32,
	FilterN: i32,
	FloatArg1: f32,
	FloatArg2: f32,
	FloatArg3: f32,
	IntArg1: i32,
	InScalar: i32,
	OutScalar: i32,
	Inhibs: i32,
	KWTA: i32,
	pad: i32,
	Geom: Geom,
}

//////// import: "scalar.go"

//////// import: "to4d.go"