// Code generated by "core generate -add-types -gosl"; DO NOT EDIT.

package v1vision

import (
	"cogentcore.org/core/enums"
)

var _GPUVarsValues = []GPUVars{0, 1, 2, 3, 4}

// GPUVarsN is the highest valid value for type GPUVars, plus one.
//
//gosl:start
const GPUVarsN GPUVars = 5

//gosl:end

var _GPUVarsValueMap = map[string]GPUVars{`OpsVar`: 0, `FiltersVar`: 1, `ImagesVar`: 2, `ValuesVar`: 3, `Values4DVar`: 4}

var _GPUVarsDescMap = map[GPUVars]string{0: ``, 1: ``, 2: ``, 3: ``, 4: ``}

var _GPUVarsMap = map[GPUVars]string{0: `OpsVar`, 1: `FiltersVar`, 2: `ImagesVar`, 3: `ValuesVar`, 4: `Values4DVar`}

// String returns the string representation of this GPUVars value.
func (i GPUVars) String() string { return enums.String(i, _GPUVarsMap) }

// SetString sets the GPUVars value from its string representation,
// and returns an error if the string is invalid.
func (i *GPUVars) SetString(s string) error {
	return enums.SetString(i, s, _GPUVarsValueMap, "GPUVars")
}

// Int64 returns the GPUVars value as an int64.
func (i GPUVars) Int64() int64 { return int64(i) }

// SetInt64 sets the GPUVars value from an int64.
func (i *GPUVars) SetInt64(in int64) { *i = GPUVars(in) }

// Desc returns the description of the GPUVars value.
func (i GPUVars) Desc() string { return enums.Desc(i, _GPUVarsDescMap) }

// GPUVarsValues returns all possible values for the type GPUVars.
func GPUVarsValues() []GPUVars { return _GPUVarsValues }

// Values returns all possible values for the type GPUVars.
func (i GPUVars) Values() []enums.Enum { return enums.Values(_GPUVarsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i GPUVars) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *GPUVars) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "GPUVars") }

var _OperationsValues = []Operations{0, 1}

// OperationsN is the highest valid value for type Operations, plus one.
//
//gosl:start
const OperationsN Operations = 2

//gosl:end

var _OperationsValueMap = map[string]Operations{`NoOp`: 0, `ConvolveImage`: 1}

var _OperationsDescMap = map[Operations]string{0: ``, 1: `ConvolveImage applies a filter to Image, writing to Values.`}

var _OperationsMap = map[Operations]string{0: `NoOp`, 1: `ConvolveImage`}

// String returns the string representation of this Operations value.
func (i Operations) String() string { return enums.String(i, _OperationsMap) }

// SetString sets the Operations value from its string representation,
// and returns an error if the string is invalid.
func (i *Operations) SetString(s string) error {
	return enums.SetString(i, s, _OperationsValueMap, "Operations")
}

// Int64 returns the Operations value as an int64.
func (i Operations) Int64() int64 { return int64(i) }

// SetInt64 sets the Operations value from an int64.
func (i *Operations) SetInt64(in int64) { *i = Operations(in) }

// Desc returns the description of the Operations value.
func (i Operations) Desc() string { return enums.Desc(i, _OperationsDescMap) }

// OperationsValues returns all possible values for the type Operations.
func OperationsValues() []Operations { return _OperationsValues }

// Values returns all possible values for the type Operations.
func (i Operations) Values() []enums.Enum { return enums.Values(_OperationsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Operations) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Operations) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "Operations")
}
