// Code generated by "gosl"; DO NOT EDIT

package v1vision

import (
	"embed"
	"fmt"
	"math"
	"unsafe"
	"cogentcore.org/core/gpu"
	"cogentcore.org/lab/tensor"
)

//go:embed shaders/*.wgsl
var shaders embed.FS

var (
	// ComputeGPU is the compute gpu device
	ComputeGPU *gpu.GPU

	// UseGPU indicates whether to use GPU vs. CPU.
	UseGPU bool
)
// GPUSystem is a GPU compute System with kernels operating on the
// same set of data variables.
var GPUSystem *gpu.ComputeSystem

// GPUVars is an enum for GPU variables, for specifying what to sync.
type GPUVars int32 //enums:enum

const (
	OpsVar GPUVars = 0
	FiltersVar GPUVars = 1
	ImagesVar GPUVars = 2
	ValuesVar GPUVars = 3
	Values4DVar GPUVars = 4
)

// Tensor stride variables
var TensorStrides tensor.Uint32

// GPUInit initializes the GPU compute system,
// configuring system(s), variables and kernels.
// It is safe to call multiple times: detects if already run.
func GPUInit() {
	if ComputeGPU != nil {
		return
	}
	gp := gpu.NewComputeGPU()
	ComputeGPU = gp
	_ = fmt.Sprintf("%g",math.NaN()) // keep imports happy
	{
		sy := gpu.NewComputeSystem(gp, "Default")
		GPUSystem = sy
		vars := sy.Vars()
		{
			sgp := vars.AddGroup(gpu.Storage, "Params")
			var vr *gpu.Var
			_ = vr
			vr = sgp.Add("TensorStrides", gpu.Uint32, 1, gpu.ComputeShader)
			vr.ReadOnly = true
			vr = sgp.AddStruct("Ops", int(unsafe.Sizeof(Op{})), 1, gpu.ComputeShader)
			vr.ReadOnly = true
			sgp.SetNValues(1)
		}
		{
			sgp := vars.AddGroup(gpu.Storage, "Filters")
			var vr *gpu.Var
			_ = vr
			vr = sgp.Add("Filters", gpu.Float32, 1, gpu.ComputeShader)
			vr.ReadOnly = true
			sgp.SetNValues(1)
		}
		{
			sgp := vars.AddGroup(gpu.Storage, "Data")
			var vr *gpu.Var
			_ = vr
			vr = sgp.Add("Images", gpu.Float32, 1, gpu.ComputeShader)
			vr = sgp.Add("Values", gpu.Float32, 1, gpu.ComputeShader)
			vr = sgp.Add("Values4D", gpu.Float32, 1, gpu.ComputeShader)
			sgp.SetNValues(1)
		}
		var pl *gpu.ComputePipeline
		pl = gpu.NewComputePipelineShaderFS(shaders, "shaders/Op0.wgsl", sy)
		pl.AddVarUsed(0, "TensorStrides")
		pl.AddVarUsed(1, "Filters")
		pl.AddVarUsed(2, "Images")
		pl.AddVarUsed(0, "Ops")
		pl.AddVarUsed(2, "Values")
		sy.Config()
	}
}

// GPURelease releases the GPU compute system resources.
// Call this at program exit.
func GPURelease() {
	if GPUSystem != nil {
		GPUSystem.Release()
		GPUSystem = nil
	}

	if ComputeGPU != nil {
		ComputeGPU.Release()
		ComputeGPU = nil
	}
}

// RunOp0 runs the Op0 kernel with given number of elements,
// on either the CPU or GPU depending on the UseGPU variable.
// Can call multiple Run* kernels in a row, which are then all launched
// in the same command submission on the GPU, which is by far the most efficient.
// MUST call RunDone (with optional vars to sync) after all Run calls.
// Alternatively, a single-shot RunOneOp0 call does Run and Done for a
// single run-and-sync case.
func RunOp0(n int) {
	if UseGPU {
		RunOp0GPU(n)
	} else {
		RunOp0CPU(n)
	}
}

// RunOp0GPU runs the Op0 kernel on the GPU. See [RunOp0] for more info.
func RunOp0GPU(n int) {
	sy := GPUSystem
	pl := sy.ComputePipelines["Op0"]
	ce, _ := sy.BeginComputePass()
	pl.Dispatch1D(ce, n, 64)
}

// RunOp0CPU runs the Op0 kernel on the CPU.
func RunOp0CPU(n int) {
	gpu.VectorizeFunc(0, n, Op0)
}

// RunOneOp0 runs the Op0 kernel with given number of elements,
// on either the CPU or GPU depending on the UseGPU variable.
// This version then calls RunDone with the given variables to sync
// after the Run, for a single-shot Run-and-Done call. If multiple kernels
// can be run in sequence, it is much more efficient to do multiple Run*
// calls followed by a RunDone call.
func RunOneOp0(n int, syncVars ...GPUVars) {
	if UseGPU {
		RunOp0GPU(n)
		RunDone(syncVars...)
	} else {
		RunOp0CPU(n)
	}
}
// RunDone must be called after Run* calls to start compute kernels.
// This actually submits the kernel jobs to the GPU, and adds commands
// to synchronize the given variables back from the GPU to the CPU.
// After this function completes, the GPU results will be available in 
// the specified variables.
func RunDone(syncVars ...GPUVars) {
	if !UseGPU {
		return
	}
	sy := GPUSystem
	sy.ComputeEncoder.End()
	ReadFromGPU(syncVars...)
	sy.EndComputePass()
	SyncFromGPU(syncVars...)
}

// ToGPU copies given variables to the GPU for the system.
func ToGPU(vars ...GPUVars) {
	if !UseGPU {
		return
	}
	sy := GPUSystem
	syVars := sy.Vars()
	for _, vr := range vars {
		switch vr {
		case OpsVar:
			v, _ := syVars.ValueByIndex(0, "Ops", 0)
			gpu.SetValueFrom(v, Ops)
		case FiltersVar:
			v, _ := syVars.ValueByIndex(1, "Filters", 0)
			gpu.SetValueFrom(v, Filters.Values)
		case ImagesVar:
			v, _ := syVars.ValueByIndex(2, "Images", 0)
			gpu.SetValueFrom(v, Images.Values)
		case ValuesVar:
			v, _ := syVars.ValueByIndex(2, "Values", 0)
			gpu.SetValueFrom(v, Values.Values)
		case Values4DVar:
			v, _ := syVars.ValueByIndex(2, "Values4D", 0)
			gpu.SetValueFrom(v, Values4D.Values)
		}
	}
}
// RunGPUSync can be called to synchronize data between CPU and GPU.
// Any prior ToGPU* calls will execute to send data to the GPU,
// and any subsequent RunDone* calls will copy data back from the GPU.
func RunGPUSync() {
	if !UseGPU {
		return
	}
	sy := GPUSystem
	sy.BeginComputePass()
}

// ToGPUTensorStrides gets tensor strides and starts copying to the GPU.
func ToGPUTensorStrides() {
	if !UseGPU {
		return
	}
	sy := GPUSystem
	syVars := sy.Vars()
	TensorStrides.SetShapeSizes(40)
	TensorStrides.SetInt1D(Filters.Shape().Strides[0], 0)
	TensorStrides.SetInt1D(Filters.Shape().Strides[1], 1)
	TensorStrides.SetInt1D(Filters.Shape().Strides[2], 2)
	TensorStrides.SetInt1D(Filters.Shape().Strides[3], 3)
	TensorStrides.SetInt1D(Images.Shape().Strides[0], 10)
	TensorStrides.SetInt1D(Images.Shape().Strides[1], 11)
	TensorStrides.SetInt1D(Images.Shape().Strides[2], 12)
	TensorStrides.SetInt1D(Images.Shape().Strides[3], 13)
	TensorStrides.SetInt1D(Values.Shape().Strides[0], 20)
	TensorStrides.SetInt1D(Values.Shape().Strides[1], 21)
	TensorStrides.SetInt1D(Values.Shape().Strides[2], 22)
	TensorStrides.SetInt1D(Values.Shape().Strides[3], 23)
	TensorStrides.SetInt1D(Values.Shape().Strides[4], 24)
	TensorStrides.SetInt1D(Values4D.Shape().Strides[0], 30)
	TensorStrides.SetInt1D(Values4D.Shape().Strides[1], 31)
	TensorStrides.SetInt1D(Values4D.Shape().Strides[2], 32)
	TensorStrides.SetInt1D(Values4D.Shape().Strides[3], 33)
	TensorStrides.SetInt1D(Values4D.Shape().Strides[4], 34)
	v, _ := syVars.ValueByIndex(0, "TensorStrides", 0)
	gpu.SetValueFrom(v, TensorStrides.Values)
}

// ReadFromGPU starts the process of copying vars to the GPU.
func ReadFromGPU(vars ...GPUVars) {
	sy := GPUSystem
	syVars := sy.Vars()
	for _, vr := range vars {
		switch vr {
		case OpsVar:
			v, _ := syVars.ValueByIndex(0, "Ops", 0)
			v.GPUToRead(sy.CommandEncoder)
		case FiltersVar:
			v, _ := syVars.ValueByIndex(1, "Filters", 0)
			v.GPUToRead(sy.CommandEncoder)
		case ImagesVar:
			v, _ := syVars.ValueByIndex(2, "Images", 0)
			v.GPUToRead(sy.CommandEncoder)
		case ValuesVar:
			v, _ := syVars.ValueByIndex(2, "Values", 0)
			v.GPUToRead(sy.CommandEncoder)
		case Values4DVar:
			v, _ := syVars.ValueByIndex(2, "Values4D", 0)
			v.GPUToRead(sy.CommandEncoder)
		}
	}
}

// SyncFromGPU synchronizes vars from the GPU to the actual variable.
func SyncFromGPU(vars ...GPUVars) {
	sy := GPUSystem
	syVars := sy.Vars()
	for _, vr := range vars {
		switch vr {
		case OpsVar:
			v, _ := syVars.ValueByIndex(0, "Ops", 0)
			v.ReadSync()
			gpu.ReadToBytes(v, Ops)
		case FiltersVar:
			v, _ := syVars.ValueByIndex(1, "Filters", 0)
			v.ReadSync()
			gpu.ReadToBytes(v, Filters.Values)
		case ImagesVar:
			v, _ := syVars.ValueByIndex(2, "Images", 0)
			v.ReadSync()
			gpu.ReadToBytes(v, Images.Values)
		case ValuesVar:
			v, _ := syVars.ValueByIndex(2, "Values", 0)
			v.ReadSync()
			gpu.ReadToBytes(v, Values.Values)
		case Values4DVar:
			v, _ := syVars.ValueByIndex(2, "Values4D", 0)
			v.ReadSync()
			gpu.ReadToBytes(v, Values4D.Values)
		}
	}
}

// GetOps returns a pointer to the given global variable: 
// [Ops] []Op at given index. This directly processed in the GPU code,
// so this function call is an equivalent for the CPU.
func GetOps(idx uint32) *Op {
	return &Ops[idx]
}
