// Code generated by "goal build"; DO NOT EDIT.
//line logrenorm.goal:1
// Copyright (c) 2019, The Emergent Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package v1vision

import (
	"cogentcore.org/core/math32"
)

// NewLogValues adds a [LogValues] operation,
// which sets [Values] to 1 + log of input Values.
// in = input Values, out = output (can be same as in),
// fn = number of filters, Geom Out sizes are used for indexing.
func (vv *V1Vision) NewLogValues(in, out, fn int, gain float32, geom *Geom) {
	op := vv.NewOp()
	op.Op = LogValues
	op.RunN = uint32(geom.Out.Y * geom.Out.X * int32(fn) * 2)
	op.InValue = int32(in)
	op.OutValue = int32(out)
	op.FilterN = int32(fn)
	op.FloatArg1 = gain
	op.Geom = *geom
}

// NewNormDiv adds a [NormDiv] operation which normalizes value
// by [Scalars] computed from NewAggScalar with given aggOp
// in = input Values. Allocates output Values and scalars as needed.
// fn = number of filters, Geom Out sizes are used for indexing.
func (vv *V1Vision) NewNormDiv(aggOp Operations, in, out, fn int, geom *Geom) {
	scout := vv.NewAggScalar(aggOp, in, fn, geom)
	op := vv.NewOp()
	op.Op = NormDiv
	op.RunN = uint32(geom.Out.Y * geom.Out.X * int32(fn) * 2)
	op.InValue = int32(in)
	op.OutValue = int32(out)
	op.InScalar = int32(scout)
	op.FilterN = int32(fn)
	op.Geom = *geom
}

//gosl:start

// LogValues is the kernel for LogValues.
func (op *Op) LogValues(i, ni int32) {
	fi := i % op.FilterN // inner
	pii := i / op.FilterN
	pi := pii % 2 // plus-minus
	ii := pii / 2
	yo := ii / op.Geom.Out.X
	xo := ii % op.Geom.Out.X

	lg := op.FloatArg1 * math32.Log(1.0+Values.Value(int(op.InValue), int(ni), int(yo), int(xo), int(pi), int(fi)))
	Values.Set(lg, int(op.OutValue), int(ni), int(yo), int(xo), int(pi), int(fi))
}

// NormDiv is the kernel for NormDiv
func (op *Op) NormDiv(i, ni int32) {
	fi := i % op.FilterN // inner
	pii := i / op.FilterN
	pi := pii % 2 // plus-minus
	ii := pii / 2
	yo := ii / op.Geom.Out.X
	xo := ii % op.Geom.Out.X

	sc := Scalars.Value(int(op.InScalar), int(ni))
	v := Values.Value(int(op.InValue), int(ni), int(yo), int(xo), int(pi), int(fi))
	if sc != 0 {
		v /= sc
	}
	Values.Set(v, int(op.OutValue), int(ni), int(yo), int(xo), int(pi), int(fi))
}

//gosl:end
