// Code generated by "goal build"; DO NOT EDIT.
//line scalar.goal:1
// Copyright (c) 2025, The Emergent Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package v1vision

// NewAggScalar adds a [SumScalar], [MeanScalar], or [MaxScalar] operation,
// which computes a [Scalars] output efficiently. Adds a Scalar output
// and returns index.
// in = input Values. Allocates output Values and scalars as needed.
// fn = number of filters, Geom Out sizes are used for indexing.
func (vv *V1Vision) NewAggScalar(aggOp Operations, in, fn int, geom *Geom) int {
	op := vv.NewOp()
	op.Op = aggOp
	op.RunN = uint32(geom.Out.Y) // aggregate over Y
	op.InValue = int32(in)
	yout := vv.NewValues(int(geom.Out.Y), 1, 1) // intermediate y output
	op.OutValue = int32(yout)
	out := vv.NewScalar(1)
	op.OutScalar = int32(out)
	op.FilterN = int32(fn)
	op.Geom = *geom
	return out
}

//gosl:start

// note: multiple sub-steps for scalar integration is slower up to 512 x 512 v1gabor images

// const ScalarSteps = 2
//
// func ScalarStart(i, n int32) int32 {
// 	ssz := n / ScalarSteps
// 	return i * ssz
// }
//
// func ScalarEnd(i, n int32) int32 {
// 	ssz := n / ScalarSteps
// 	if i == n-1 {
// 		return n
// 	}
// 	return (i+1) * ssz
// }

// MaxScalarX is the first kernel for MaxScalar,
// operating over X rows.
func MaxScalarX(i uint32) { //gosl:kernel
	op := GetCurOp(0)
	if i >= op.RunN*op.NData {
		return
	}
	ri := int32(i % op.RunN)
	ni := int32(i / op.RunN)
	mx := float32(0)
	for x := range op.Geom.Out.X {
		for pi := range 2 {
			for fi := range op.FilterN {
				v := Values.Value(int(op.InValue), int(ni), int(ri), int(x), int(pi), int(fi))
				mx = max(mx, v)
			}
		}
	}
	Values.Set(mx, int(op.OutValue), int(ni), int(ri), int(0), int(0), int(0))
}

// MaxScalarY is the second kernel for MaxScalar.
// operating over Y intermediate sum.
func MaxScalarY(i uint32) { //gosl:kernel
	op := GetCurOp(0)
	if i >= op.NData {
		return
	}
	ni := int32(i)
	mx := float32(0)
	for y := range op.Geom.Out.Y {
		v := Values.Value(int(op.OutValue), int(ni), int(y), int(0), int(0), int(0))
		mx = max(mx, v)
	}
	Scalars.Set(mx, int(op.OutScalar), int(ni))
}

// SumScalarX is the first kernel for SumScalar,
// operating over X rows.
func SumScalarX(i uint32) { //gosl:kernel
	op := GetCurOp(0)
	if i >= op.RunN*op.NData {
		return
	}
	ri := int32(i % op.RunN)
	ni := int32(i / op.RunN)
	sum := float32(0)
	for x := range op.Geom.Out.X {
		for pi := range 2 {
			for fi := range op.FilterN {
				v := Values.Value(int(op.InValue), int(ni), int(ri), int(x), int(pi), int(fi))
				sum += v
			}
		}
	}
	Values.Set(sum, int(op.OutValue), int(ni), int(ri), int(0), int(0), int(0))
}

// SumScalarY is the second kernel for SumScalar.
// operating over Y intermediate sum.
func SumScalarY(i uint32) { //gosl:kernel
	op := GetCurOp(0)
	if i >= op.NData {
		return
	}
	ni := int32(i)
	sum := float32(0)
	for y := range op.Geom.Out.Y {
		v := Values.Value(int(op.OutValue), int(ni), int(y), int(0), int(0), int(0))
		sum += v
	}
	Scalars.Set(sum, int(op.OutScalar), int(ni))
}

// MeanScalarY is the second kernel for MeanScalar.
// operating over Y intermediate sum.
func MeanScalarY(i uint32) { //gosl:kernel
	op := GetCurOp(0)
	if i >= op.NData {
		return
	}
	ni := int32(i)
	sum := float32(0)
	for y := range op.Geom.Out.Y {
		v := Values.Value(int(op.OutValue), int(ni), int(y), int(0), int(0), int(0))
		sum += v
	}
	sum /= float32(op.Geom.Out.Y * op.Geom.Out.X * op.FilterN * 2)
	Scalars.Set(sum, int(op.OutScalar), int(ni))
}

//gosl:end
