// Code generated by "core generate -add-types"; DO NOT EDIT.

package main

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "main.Vis", IDName: "vis", Doc: "Vis encapsulates specific visual processing pipeline in\nuse in a given case -- can add / modify this as needed", Directives: []types.Directive{{Tool: "types", Directive: "add"}}, Methods: []types.Method{{Name: "RenderFrames", Doc: "RenderFrames renders the frames", Directives: []types.Directive{{Tool: "types", Directive: "add"}}}, {Name: "Filter", Doc: "Filter is overall method to run filters on current image file name\nloads the image from ImageFile and then runs filters", Directives: []types.Directive{{Tool: "types", Directive: "add"}}, Returns: []string{"error"}}}, Fields: []types.Field{{Name: "NFrames", Doc: "NFrames is the number of frames to render per trial."}, {Name: "ImageSize", Doc: "target image size to use."}, {Name: "Bar", Doc: "Bar is the size of the moving bar."}, {Name: "Velocity", Doc: "Velocity is the motion direction vector."}, {Name: "Start", Doc: "Start is the starting position."}, {Name: "Pos", Doc: "Pos is current position"}, {Name: "Motion", Doc: "Motion parameters"}, {Name: "DoG", Doc: "LGN DoG filter parameters"}, {Name: "Geom", Doc: "geometry of input, output"}, {Name: "ImageTsr", Doc: "input image as tensor"}, {Name: "DoGFilter", Doc: "DoG filter tensor -- has 3 filters (on, off, net)"}, {Name: "DoGTab", Doc: "DoG filter table (view only)"}, {Name: "DoGOutTsr", Doc: "DoG filter output tensor"}, {Name: "Slow"}, {Name: "Fast"}, {Name: "MotionOut"}}})
