// Code generated by "core generate -add-types"; DO NOT EDIT.

package main

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "main.Vis", IDName: "vis", Directives: []types.Directive{{Tool: "types", Directive: "add"}}, Methods: []types.Method{{Name: "Filter", Doc: "Filter is overall method to run filters on current image file name\nloads the image from ImageFile and then runs filters", Directives: []types.Directive{{Tool: "types", Directive: "add"}}, Returns: []string{"error"}}}, Embeds: []types.Field{{Name: "V1cMulti"}}, Fields: []types.Field{{Name: "ImageFile", Doc: "ImageFile is the name of image file to operate on."}, {Name: "StdImage", Doc: "StdImage manages images."}, {Name: "tabView"}}})
