// Code generated by "core generate -add-types -gosl"; DO NOT EDIT.

package dog

import (
	"cogentcore.org/core/enums"
)

var _FiltersValues = []Filters{0, 1, 2}

// FiltersN is the highest valid value for type Filters, plus one.
//
//gosl:start
const FiltersN Filters = 3

//gosl:end

var _FiltersValueMap = map[string]Filters{`On`: 0, `Off`: 1, `Net`: 2}

var _FiltersDescMap = map[Filters]string{0: ``, 1: ``, 2: ``}

var _FiltersMap = map[Filters]string{0: `On`, 1: `Off`, 2: `Net`}

// String returns the string representation of this Filters value.
func (i Filters) String() string { return enums.String(i, _FiltersMap) }

// SetString sets the Filters value from its string representation,
// and returns an error if the string is invalid.
func (i *Filters) SetString(s string) error {
	return enums.SetString(i, s, _FiltersValueMap, "Filters")
}

// Int64 returns the Filters value as an int64.
func (i Filters) Int64() int64 { return int64(i) }

// SetInt64 sets the Filters value from an int64.
func (i *Filters) SetInt64(in int64) { *i = Filters(in) }

// Desc returns the description of the Filters value.
func (i Filters) Desc() string { return enums.Desc(i, _FiltersDescMap) }

// FiltersValues returns all possible values for the type Filters.
func FiltersValues() []Filters { return _FiltersValues }

// Values returns all possible values for the type Filters.
func (i Filters) Values() []enums.Enum { return enums.Values(_FiltersValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Filters) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Filters) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "Filters") }
