ID = 'com.emer.vision.v2'
Name = 'vision'
Type = 'Library'
Version = 'v2.0.0-dev0.0.8'

[Generate]
  [Generate.Gtigen]
    AddTypes = true

[Release]
  Package = 'vfilter'
  VersionFile = 'vfilter/version.go'
