ID = 'com.emer.vision.v2'
Name = 'vision'
Type = 'Library'
Version = 'v2.0.0-dev0.0.6'

[Generate]
  [Generate.Enumgen]
    AcceptLower = true
    LineComment = true

  [Generate.Gtigen]
    AddTypes = true

[Release]
  Package = 'vfilter'
  VersionFile = 'vfilter/version.go'

[Web]
  LoadingLabel = ''
  RandomVersion = false
